"""Add new fields to User model

Revision ID: 0fec6a7d7fc2
Revises: 32b4595ba9b6
Create Date: 2025-06-04 05:12:11.451908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fec6a7d7fc2'
down_revision = '32b4595ba9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('floor_map_roles',
    # sa.Column('floor_map_id', sa.Integer(), nullable=False),
    # sa.Column('role_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['floor_map_id'], ['floor_map.id'], ),
    # sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    # sa.PrimaryKeyConstraint('floor_map_id', 'role_id')
    # )
    # with op.batch_alter_table('booking_settings', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('past_booking_time_adjustment_hours', sa.Integer(), nullable=True))

    # with op.batch_alter_table('floor_map', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('offset_x', sa.Integer(), nullable=False))
    #     batch_op.add_column(sa.Column('offset_y', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instagram_id', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_user_instagram_id', ['instagram_id'])
        batch_op.create_unique_constraint('uq_user_facebook_id', ['facebook_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_instagram_id', type_='unique')
        batch_op.drop_constraint('uq_user_facebook_id', type_='unique')
        batch_op.drop_column('instagram_id')
        batch_op.drop_column('facebook_id')
        batch_op.drop_column('position')
        batch_op.drop_column('department')
        batch_op.drop_column('section')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # with op.batch_alter_table('floor_map', schema=None) as batch_op:
    #     batch_op.drop_column('offset_y')
    #     batch_op.drop_column('offset_x')

    # with op.batch_alter_table('booking_settings', schema=None) as batch_op:
    #     batch_op.drop_column('past_booking_time_adjustment_hours')

    # op.drop_table('floor_map_roles')
    # ### end Alembic commands ###
