"""add_allow_check_in_without_pin_to_bookingsettings

Revision ID: 1a2b3c4d5e6f
Revises:
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_settings', sa.Column('allow_check_in_without_pin', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_settings', 'allow_check_in_without_pin')
    # ### end Alembic commands ###
