"""Remove floor_map_roles table and FloorMap-Role relationship

Revision ID: 2576bcfeaef5
Revises: 32b4595ba9b6
Create Date: 2025-06-04 04:42:39.764783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2576bcfeaef5'
down_revision = '32b4595ba9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_booking_time_adjustment_hours', sa.Integer(), nullable=True))

    with op.batch_alter_table('floor_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset_x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('offset_y', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor_map', schema=None) as batch_op:
        batch_op.drop_column('offset_y')
        batch_op.drop_column('offset_x')

    with op.batch_alter_table('booking_settings', schema=None) as batch_op:
        batch_op.drop_column('past_booking_time_adjustment_hours')

    # ### end Alembic commands ###
