"""Remove floor_map_roles table and FloorMap-Role relationship

Revision ID: 2576bcfeaef5
Revises: 32b4595ba9b6
Create Date: 2025-06-04 04:42:39.764783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2576bcfeaef5'
down_revision = '32b4595ba9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    # Check for 'past_booking_time_adjustment_hours' in 'booking_settings'
    booking_settings_columns = [col['name'] for col in inspector.get_columns('booking_settings')]
    if 'past_booking_time_adjustment_hours' not in booking_settings_columns:
        with op.batch_alter_table('booking_settings', schema=None) as batch_op:
            batch_op.add_column(sa.Column('past_booking_time_adjustment_hours', sa.Integer(), nullable=True))

    # For 'floor_map' table, apply similar checks for 'offset_x' and 'offset_y'
    floor_map_columns = [col['name'] for col in inspector.get_columns('floor_map')]
    if 'offset_x' not in floor_map_columns:
        with op.batch_alter_table('floor_map', schema=None) as batch_op:
            batch_op.add_column(sa.Column('offset_x', sa.Integer(), nullable=False))

    if 'offset_y' not in floor_map_columns:
        with op.batch_alter_table('floor_map', schema=None) as batch_op:
            batch_op.add_column(sa.Column('offset_y', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor_map', schema=None) as batch_op:
        batch_op.drop_column('offset_y')
        batch_op.drop_column('offset_x')

    with op.batch_alter_table('booking_settings', schema=None) as batch_op:
        batch_op.drop_column('past_booking_time_adjustment_hours')

    # ### end Alembic commands ###
