"""add check_in_token and expires_at to booking

Revision ID: 435ead8519eb
Revises: 0fec6a7d7fc2
Create Date: 2025-06-06 15:51:55.125794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435ead8519eb'
down_revision = '0fec6a7d7fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('check_in_token_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_allowed_role_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_pin', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('current_pin')
        batch_op.drop_column('map_allowed_role_ids')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('check_in_token_expires_at')
        batch_op.drop_column('check_in_token')

    # ### end Alembic commands ###
