"""add_display_order_to_floor_map

Revision ID: 44d956e882f7
Revises:
Create Date: 2025-06-19 13:12:32.694690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d956e882f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_past_bookings', sa.Boolean(), nullable=True),
    sa.Column('max_booking_days_in_future', sa.Integer(), nullable=True),
    sa.Column('allow_multiple_resources_same_time', sa.Boolean(), nullable=True),
    sa.Column('max_bookings_per_user', sa.Integer(), nullable=True),
    sa.Column('enable_check_in_out', sa.Boolean(), nullable=True),
    sa.Column('past_booking_time_adjustment_hours', sa.Integer(), nullable=True),
    sa.Column('check_in_minutes_before', sa.Integer(), nullable=False),
    sa.Column('check_in_minutes_after', sa.Integer(), nullable=False),
    sa.Column('checkin_reminder_minutes_before', sa.Integer(), nullable=False),
    sa.Column('pin_auto_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('pin_length', sa.Integer(), nullable=False),
    sa.Column('pin_allow_manual_override', sa.Boolean(), nullable=False),
    sa.Column('allow_check_in_without_pin', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('resource_checkin_url_requires_login', sa.Boolean(), nullable=False),
    sa.Column('map_resource_opacity', sa.Float(), nullable=False),
    sa.Column('enable_auto_checkout', sa.Boolean(), nullable=False),
    sa.Column('auto_checkout_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('global_time_offset_hours', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_release_if_not_checked_in_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('offset_x', sa.Integer(), nullable=False),
    sa.Column('offset_y', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_data_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_filename')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('google_email', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('facebook_id', sa.String(length=200), nullable=True),
    sa.Column('instagram_id', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('facebook_id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('instagram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('booking_restriction', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('allowed_user_ids', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('is_under_maintenance', sa.Boolean(), nullable=False),
    sa.Column('maintenance_until', sa.DateTime(), nullable=True),
    sa.Column('max_recurrence_count', sa.Integer(), nullable=True),
    sa.Column('scheduled_status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_status_at', sa.DateTime(), nullable=True),
    sa.Column('floor_map_id', sa.Integer(), nullable=True),
    sa.Column('map_coordinates', sa.Text(), nullable=True),
    sa.Column('map_allowed_role_ids', sa.Text(), nullable=True),
    sa.Column('current_pin', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['floor_map_id'], ['floor_map.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=200), nullable=True),
    sa.Column('admin_deleted_message', sa.String(length=255), nullable=True),
    sa.Column('check_in_token', sa.String(length=255), nullable=True),
    sa.Column('check_in_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('checkin_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('booking_display_start_time', sa.Time(), nullable=True),
    sa.Column('booking_display_end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'start_time', 'end_time', name='uq_booking_resource_time')
    )
    op.create_table('resource_pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('pin_value', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'pin_value', name='uq_resource_pin_value')
    )
    op.create_table('resource_roles',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'role_id')
    )
    op.create_table('waitlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlist_entry')
    op.drop_table('resource_roles')
    op.drop_table('resource_pin')
    op.drop_table('booking')
    op.drop_table('user_roles')
    op.drop_table('resource')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('floor_map')
    op.drop_table('booking_settings')
    # ### end Alembic commands ###
