"""add_map_resource_opacity_to_booking_settings

Revision ID: eb52bf259bd2
Revises: a7b371de7b45
Create Date: 2025-06-08 07:55:35.649465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb52bf259bd2'
down_revision = 'a7b371de7b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_resource_opacity', sa.Float(), nullable=False, server_default='0.7'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_settings', schema=None) as batch_op:
        batch_op.drop_column('map_resource_opacity')

    # ### end Alembic commands ###
